{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  labels:
    app: {{ .Values.statefulset.name }}
spec:
  serviceName: "{{ .Values.statefulset.name }}"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.name }}
      annotations:
        nersc.slurm/account: "{{ .Values.statefulset.account }}"
        nersc.sf/credentialSecretName: "{{ .Values.statefulset.credentialSecretName }}"
{{- with .Values.statefulset.credentialSecretKey }}
        nersc.sf/credentialSecretKey: "{{ . }}"
{{- end }}
{{- with .Values.statefulset.transferMode }}
        nersc.sf/transferMode: "{{ . }}"
{{- end }}
{{- with .Values.statefulset.scratchBase }}
        nersc.sf/scratchBase: "{{ . }}"
{{- end }}
{{- with .Values.statefulset.globusCredentialSecretName }}
        globus.api/credentialSecretName: "{{ . }}"
{{- end }}
{{- with .Values.statefulset.globusCredentialSecretKey }}
        globus.api/credentialSecretKey: "{{ . }}"
{{- end }}
{{- with .Values.statefulset.globusStagingCollectionID }}
        globus.api/stagingCollectionID: "{{ . }}"
{{- end }}
{{- with .Values.statefulset.globusScope }}
        globus.api/scope: "{{ . }}"
{{- end }}
{{- if eq (default "globus" .Values.statefulset.transferMode) "globus" }}
        globus.api/inputSource: "{{ .Values.statefulset.inputSource }}"
{{- else }}
        nersc.sf/inputSource: "{{ .Values.statefulset.inputSource }}"
{{- end }}
{{- with .Values.statefulset.inputVolume }}
        nersc.sf/inputVolume: "{{ . }}"
{{- end }}
{{- if eq (default "globus" .Values.statefulset.transferMode) "globus" }}
        globus.api/outputDest: "{{ .Values.statefulset.outputDest }}"
{{- else }}
        nersc.sf/outputDest: "{{ .Values.statefulset.outputDest }}"
{{- end }}
{{- with .Values.statefulset.outputVolume }}
        nersc.sf/outputVolume: "{{ . }}"
{{- end }}
        nersc.sf/stageOut: "{{ .Values.statefulset.stageOut }}"
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.statefulset.nodeSelector | quote }}
      containers:
      - name: {{ .Values.statefulset.container.name }}
        image: {{ .Values.statefulset.container.image | quote }}
        command:
{{ toYaml .Values.statefulset.container.command | indent 10 }}
        args:
{{ toYaml .Values.statefulset.container.args | indent 10 }}
        volumeMounts:
{{- range .Values.statefulset.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath | quote }}
          readOnly: {{ .readOnly }}
{{- end }}
      volumes:
{{- range .Values.statefulset.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .claimName | quote }}
{{- end }}
{{- end }}
