apiVersion: v1
kind: Secret
metadata:
  name: globus-refresh-token
type: Opaque
stringData:
  client_id: "replace-with-globus-client-id"
  client_secret: "replace-with-globus-client-secret"
  refresh_token: "replace-with-globus-transfer-refresh-token"
